osism/zuul-jobs

- roles/ansible-lint/tasks/main.yml
> Change installation order

- roles/ansible-lint/tasks/main.yml
> Add extra_args to ansible-lint

- roles/ansible-lint/tasks/main.yml
> Modify ansible-lint job

- roles/ansible-lint/tasks/main.yml
> Add when condition for ansible-lint

- roles/ansible-lint/tasks/main.yml
- roles/flake8/README.md
- roles/flake8/defaults/main.yml
- roles/flake8/tasks/main.yml
The name of the used tool is flake8 and not flake8lint
> Rename flake8lint to flake8

- .zuul.yaml
- playbooks/devstack/run.yaml
- roles/devstack/README.md
- roles/devstack/defaults/main.yml
- roles/devstack/tasks/main.yml
Import of osism/openstack-action.
ensure-devstack is not enough for us as we want to configure services etc.
> Add devstack job

- roles/ansible-lint/defaults/main.yml
- roles/ansible-lint/tasks/main.yml
> ansible-lint: use ansible-core

- roles/ansible-lint/tasks/main.yml
> Ansible-lint: Fix linting

- roles/ansible-lint/tasks/main.yml
Signed-off-by: Tim Beermann <beermann@osism.tech>
> debug ansible lint

- roles/ansible-lint/tasks/main.yml
Signed-off-by: Tim Beermann <beermann@osism.tech>
> fix ansible-linting

- .ansible-lint
- .ansible-lint-rules/osism_attribute_order.py
- .ansible-lint-rules/osism_fqcn.py
- playbooks/ansible-lint/run.yaml
- playbooks/devstack/run.yaml
- playbooks/flake8/run.yaml
- playbooks/hadolint/run.yaml
- playbooks/yamllint/run.yaml
- roles/ansible-lint/tasks/main.yml
> Refactor: Ansible-lint custom rules

- playbooks/dcolicense/run.yaml
- roles/dcolicense/defaults/main.yml
- roles/dcolicense/tasks/main.yml
> DCO License check: Add Playbook and Role

- .zuul.yaml
> Add dcolicense job to .zuul.yaml

- .ansible-lint-rules/osism_fqcn_list.yaml
Add community.general.filesystem to the list
> Ansible-lint: osism fqcn check

- .ansible-lint-rules/osism_fqcn_list.yaml
> Add kolla_toolbox to osism fqcn list

- roles/ansible-lint/files/osism_fqcn_list.yaml
> Add modules to osism fqcn checks

- roles/ansible-lint/files/osism_fqcn_list.yaml
> Add ansible fqcn to the osism fqcn list

- roles/ansible-lint/tasks/main.yml
> Ensure that jmespath is installed

- .ansible-lint
- roles/flake8/tasks/main.yml
- roles/hadolint/tasks/main.yml
- roles/yamllint/tasks/main.yml
- Refactor some code to fix issues
- Delete rules
- Partly osism/issues#496
> Ansible-lint: Delete not needed rules

- .zuul.yaml
- playbooks/ansible-molecule/run.yaml
- roles/ansible-molecule/README.md
- roles/ansible-molecule/defaults/main.yml
- roles/ansible-molecule/tasks/main.yml
Add the ansible-molecule role: https://github.com/osism/ansible-collection-commons
Which was previously a GitHub Workflow.
> Add Ansible-molecule job

- .ansible-lint-rules/osism_fqcn_list.yaml
Also sort the community.general list.
> ansible-lint: add community.general.pam_limits

- roles/python-black/tasks/main.yml
> Modify Python-black role

- .ansible-lint-rules/osism_fqcn_list.yaml
- roles/ansible-lint/files/osism_fqcn_list.yaml
Related to osism/ansible-collection-commons#578
> ansible-lint: add ansible.builtin.systemd_service

- roles/ansible-lint/files/osism_fqcn_list.yaml
Related to osism/ansible-collection-services#1296
> ansible-lint: add kubernetes.core.helm

- roles/ansible-molecule/tasks/main.yml
This reverts commit ad50cf9385b94d66c4f20afff8999a786294b39b.
> Revert "ansible-molecule: use single step again"

- .zuul.yaml
This shoud fix the following issue:
An unknown error occurred: 'CustomHTTPSConnection' object has no attribute 'cert_file'
> Use Ansible 8 for the hadolint job

- roles/ansible-molecule/defaults/main.yml
- roles/ansible-molecule/tasks/main.yml
- roles/ansible-molecule/vars/Ubuntu-jammy.yml
Revert f779120a50acd20d9ffb9566323efe707dca6697
> ansible-molecule: set python binary
